# Generated by Django 5.1.1 on 2025-07-15 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveblog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liveblog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='liveblog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liveblog',
            name='event_status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('ended', 'Ended'), ('scheduled', 'Scheduled')], default='ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='liveblog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
