# Generated by Django 4.2.7 on 2025-07-22 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liveblog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liveblog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='liveblog',
            index=models.Index(fields=['author', 'timestamp'], name='liveblog_li_author__5743c9_idx'),
        ),
        migrations.AddIndex(
            model_name='liveblog',
            index=models.Index(fields=['event_status'], name='liveblog_li_event_s_16d717_idx'),
        ),
        migrations.AddIndex(
            model_name='liveblog',
            index=models.Index(fields=['timestamp'], name='liveblog_li_timesta_ac6525_idx'),
        ),
    ]
