# Generated by Django 4.2.7 on 2025-07-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveblog', '0002_liveblog_is_active_alter_liveblog_author_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='liveblog',
            index=models.Index(fields=['author', 'timestamp'], name='liveblog_li_author__5743c9_idx'),
        ),
        migrations.AddIndex(
            model_name='liveblog',
            index=models.Index(fields=['event_status'], name='liveblog_li_event_s_16d717_idx'),
        ),
        migrations.AddIndex(
            model_name='liveblog',
            index=models.Index(fields=['timestamp'], name='liveblog_li_timesta_ac6525_idx'),
        ),
    ]
