# Generated by Django 4.2.7 on 2025-07-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveblog', '0003_liveblog_liveblog_li_author__5743c9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='liveblog/images/'),
        ),
        migrations.AddField(
            model_name='liveblog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='liveblog/videos/'),
        ),
    ]
