# Generated by Django 4.2.7 on 2025-07-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_email_unique'),
        ('users', '0003_remove_customuser_avatar_alter_customuser_email'),
    ]

    operations = [
    ]
