version: '3.8'

services:
  web:
    build: .
    command: gunicorn liveblogproject.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
      - rabbitmq

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  celery:
    build: .
    command: celery -A liveblogproject worker -l info
    volumes:
      - .:/app
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
      - rabbitmq

  celery-beat:
    build: .
    command: celery -A liveblogproject beat -l info
    volumes:
      - .:/app
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data:
  rabbitmq_data: