# Generated by Django 5.1.1 on 2025-07-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0004_alter_notification_notification_type_report'),
        ('realtime', '0004_remove_userfollowing'),
    ]

    operations = [
    ]
