# Generated by Django 5.1.1 on 2025-07-15 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveblog', '0002_liveblog_is_active_alter_liveblog_author_and_more'),
        ('realtime', '0005_merge_20250715_0651'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='live_blog',
            new_name='liveblog',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='is_sent',
            new_name='is_email_sent',
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('COMMENT', 'Comment'), ('LIKE', 'Like'), ('FOLLOW', 'Follow'), ('POST_UPDATE', 'Post Update'), ('RATING', 'Rating'), ('REPORT', 'Report'), ('PASSWORD_RESET', 'Password Reset'), ('NEW_FOLLOWER', 'New Follower'), ('POST_LIKED', 'Post Liked')], max_length=20),
        ),
        migrations.CreateModel(
            name='PostRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('liveblog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='liveblog.liveblog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'liveblog')},
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
